// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO0KLl0WUJ2SswJ4uulda8Lb281CVyDnA',
    appId: '1:334109439527:web:8607a2914dd1843c8a4002',
    messagingSenderId: '334109439527',
    projectId: 'univ-capstone2024',
    authDomain: 'univ-capstone2024.firebaseapp.com',
    storageBucket: 'univ-capstone2024.appspot.com',
    measurementId: 'G-EY80C8374Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ1lQRHlyqJgR6hZIN6zTeZ0XIwRTkMxo',
    appId: '1:334109439527:android:5419b69498a9b5dc8a4002',
    messagingSenderId: '334109439527',
    projectId: 'univ-capstone2024',
    storageBucket: 'univ-capstone2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrO6ZuXOXPzstEupEKAzTWMvDzlM8XAAs',
    appId: '1:334109439527:ios:f1df45d2049aaeb28a4002',
    messagingSenderId: '334109439527',
    projectId: 'univ-capstone2024',
    storageBucket: 'univ-capstone2024.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrO6ZuXOXPzstEupEKAzTWMvDzlM8XAAs',
    appId: '1:334109439527:ios:f1df45d2049aaeb28a4002',
    messagingSenderId: '334109439527',
    projectId: 'univ-capstone2024',
    storageBucket: 'univ-capstone2024.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO0KLl0WUJ2SswJ4uulda8Lb281CVyDnA',
    appId: '1:334109439527:web:2eb266193e7009c88a4002',
    messagingSenderId: '334109439527',
    projectId: 'univ-capstone2024',
    authDomain: 'univ-capstone2024.firebaseapp.com',
    storageBucket: 'univ-capstone2024.appspot.com',
    measurementId: 'G-Q7W2YQSFF0',
  );

}